services:
  postgres:
    image: postgres:16
    container_name: postgres_local
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-motorent_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Motorent@123}
      POSTGRES_DB: ${POSTGRES_DB:-motorent_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit_local
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-rabbit_user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-Rabbit@123}

volumes:
  postgres_data:
